version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend
    command: npm run dev

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
